export const FALLBACK_PLAN = {
  planName: 'Athletic Foundation',
  days: [
    {
      day: 1,
      title: 'Speed & Jump',
      focus: 'Explosive power + Running form',
      time: '60 min',
      icon: '\u26A1',
      xp: 80,
      exercises: [
        {
          name: 'Wall A-Drill',
          type: 'RUNNING FORM',
          sets: '3 sets',
          reps: '20 each leg',
          durationSec: 0,
          icon: '\uD83C\uDFC3',
          cue: 'Lean into wall, drive knees in a cycling motion. When foot drops, push hip BEHIND you.',
          formChecks: ['hips extend behind', 'cycling motion', 'steady lean'],
        },
        {
          name: 'Squat Jump',
          type: 'JUMP',
          sets: '4 sets',
          reps: '8 reps',
          durationSec: 0,
          icon: '\uD83E\uDD98',
          cue: 'Sit back into squat, pause 1 sec, explode up maximally. Land soft and absorb through the legs.',
          formChecks: ['full squat depth', 'explode up', 'soft landing'],
        },
        {
          name: 'Push-Ups',
          type: 'PUSH',
          sets: '4 sets',
          reps: 'max reps',
          durationSec: 0,
          icon: '\uD83D\uDCAA',
          cue: 'Chest to floor, full lockout at top. Keep body in a straight rigid plank throughout every rep.',
          formChecks: ['straight body line', 'chest to floor', 'full lockout'],
        },
        {
          name: 'Plank Hold',
          type: 'CORE',
          sets: '3 sets',
          reps: 'hold',
          durationSec: 40,
          icon: '\uD83D\uDCCF',
          cue: 'Straight line from head to heel on forearms. Squeeze glutes and core. Breathe steadily.',
          formChecks: ['straight line', 'no hip sag', 'core braced'],
        },
        {
          name: 'Calf Raises',
          type: 'CALVES',
          sets: '4 sets',
          reps: '25 reps',
          durationSec: 0,
          icon: '\uD83E\uDDB5',
          cue: '3 seconds up on toes, 3 seconds down. Full range of motion every rep.',
          formChecks: ['full range', 'slow tempo', 'no bounce'],
        },
      ],
    },
    {
      day: 2,
      title: 'Arms & Skills',
      focus: 'Strength + Sport drills + Footwork',
      time: '65 min',
      icon: '\uD83D\uDCAA',
      xp: 85,
      exercises: [
        {
          name: 'Wide Push-Ups',
          type: 'PUSH',
          sets: '4 sets',
          reps: 'max reps',
          durationSec: 0,
          icon: '\uD83D\uDCAA',
          cue: 'Hands wider than shoulders. Shifts load to chest and outer arms for broader strength.',
          formChecks: ['wide grip', 'straight body', 'full range'],
        },
        {
          name: 'Diamond Push-Ups',
          type: 'PUSH',
          sets: '3 sets',
          reps: '8 reps',
          durationSec: 0,
          icon: '\uD83D\uDC8E',
          cue: 'Hands in diamond under chest. Hits triceps and inner chest. Slow controlled reps.',
          formChecks: ['diamond hands', 'elbows tracking', 'controlled pace'],
        },
        {
          name: 'Sit-Ups with Twist',
          type: 'CORE',
          sets: '3 sets',
          reps: '12 each side',
          durationSec: 0,
          icon: '\uD83C\uDF00',
          cue: 'At the top, rotate elbow to opposite knee. Builds rotational core for sports.',
          formChecks: ['full rotation', 'controlled descent', 'no neck strain'],
        },
        {
          name: 'Isometric Wall Curl',
          type: 'BICEPS',
          sets: '4 sets',
          reps: 'hold',
          durationSec: 10,
          icon: '\uD83D\uDCAA',
          cue: 'Press back of wrists into door frame at hip height and push UP hard. Biceps fully contracted.',
          formChecks: ['90 degree elbow', 'hard contraction', 'stable position'],
        },
        {
          name: '4-Corner Foot Tap',
          type: 'AGILITY',
          sets: '4 sets',
          reps: 'fast',
          durationSec: 30,
          icon: '\uD83D\uDC5F',
          cue: 'Mark 4 spots in a square. Tap each corner fast in sequence. Trains quick feet.',
          formChecks: ['light on feet', 'quick taps', 'proper sequence'],
        },
      ],
    },
    {
      day: 3,
      title: 'Power Day',
      focus: 'Reactive jumps + Full core',
      time: '65 min',
      icon: '\uD83D\uDE80',
      xp: 90,
      exercises: [
        {
          name: 'Depth Drop',
          type: 'JUMP',
          sets: '3 sets',
          reps: '8 reps',
          durationSec: 0,
          icon: '\u2B07\uFE0F',
          cue: 'Step off a low ledge, land as quietly as possible absorbing through legs.',
          formChecks: ['quiet landing', 'soft knees', 'balance on landing'],
        },
        {
          name: 'Tuck Jump',
          type: 'JUMP',
          sets: '3 sets',
          reps: '8 reps',
          durationSec: 0,
          icon: '\uD83E\uDD38',
          cue: 'Jump and pull both knees to chest in the air. Hips pull the knees.',
          formChecks: ['knees to chest', 'hip pull', 'soft landing'],
        },
        {
          name: 'Hollow Body Hold',
          type: 'CORE',
          sets: '4 sets',
          reps: 'hold',
          durationSec: 25,
          icon: '\uD83C\uDF4C',
          cue: 'Lie flat, lower back pressed hard to floor, arms overhead, legs raised.',
          formChecks: ['back flat to floor', 'arms overhead', 'legs raised'],
        },
        {
          name: 'V-Ups',
          type: 'CORE',
          sets: '3 sets',
          reps: '10 reps',
          durationSec: 0,
          icon: '\u270C\uFE0F',
          cue: 'From flat, lift both straight legs and arms to meet in a V. Controlled and slow.',
          formChecks: ['straight legs', 'controlled', 'meet at top'],
        },
        {
          name: 'Decline Push-Ups',
          type: 'PUSH',
          sets: '3 sets',
          reps: 'max reps',
          durationSec: 0,
          icon: '\uD83D\uDCD0',
          cue: 'Feet elevated on a chair. Push-up from there. Hits upper chest and shoulders.',
          formChecks: ['feet elevated', 'straight body', 'full range'],
        },
      ],
    },
    {
      day: 4,
      title: 'Skills & Recovery',
      focus: 'Mobility + Agility drills',
      time: '55 min',
      icon: '\uD83E\uDD38',
      xp: 70,
      exercises: [
        {
          name: "World's Greatest Stretch",
          type: 'MOBILITY',
          sets: '2 rounds',
          reps: '5 each side',
          durationSec: 0,
          icon: '\uD83C\uDF0D',
          cue: 'Deep lunge, drop same-side elbow to floor next to front foot, rotate arm up to sky.',
          formChecks: ['deep lunge', 'elbow to floor', 'full rotation up'],
        },
        {
          name: 'Hip Flexor Lunge Hold',
          type: 'MOBILITY',
          sets: '3 sets',
          reps: 'hold',
          durationSec: 30,
          icon: '\uD83E\uDDD8',
          cue: 'Deep lunge, back knee on floor, push hips forward. Stay tall.',
          formChecks: ['back knee down', 'hips forward', 'tall posture'],
        },
        {
          name: 'Hip-Shoulder Separation',
          type: 'THROWING',
          sets: '3 sets',
          reps: '10 each',
          durationSec: 0,
          icon: '\uD83C\uDFC8',
          cue: 'Arms crossed on chest. Rotate hips while shoulders stay still.',
          formChecks: ['hips separate from shoulders', 'controlled rotation', 'full range'],
        },
        {
          name: 'Slow Plank Hold',
          type: 'CORE',
          sets: '3 sets',
          reps: 'hold',
          durationSec: 40,
          icon: '\uD83D\uDCCF',
          cue: 'Recovery day plank \u2014 focus on breathing. Inhale through nose, exhale through mouth.',
          formChecks: ['straight line', 'steady breath', 'no sagging'],
        },
        {
          name: 'T-Drill',
          type: 'AGILITY',
          sets: '5 rounds',
          reps: 'each way',
          durationSec: 0,
          icon: '\u271D\uFE0F',
          cue: 'Sprint 10m, shuffle left 5m, shuffle right 10m, shuffle back, backpedal out.',
          formChecks: ['stay low', "don't cross feet", 'quick direction change'],
        },
      ],
    },
    {
      day: 5,
      title: 'Benchmark Day',
      focus: 'Test everything \u2014 record all numbers',
      time: '70 min',
      icon: '\uD83C\uDFC6',
      xp: 100,
      exercises: [
        {
          name: 'Max Vertical Jump',
          type: 'BENCHMARK',
          sets: '5 attempts',
          reps: 'mark the wall',
          durationSec: 0,
          icon: '\uD83C\uDFC6',
          cue: 'Jump as high as you can and mark the wall. Track this EVERY Friday.',
          formChecks: ['max effort', 'arm swing', 'soft landing'],
        },
        {
          name: 'Push-Ups \u2014 Max Set',
          type: 'BENCHMARK',
          sets: '1 max set',
          reps: 'to failure',
          durationSec: 0,
          icon: '\uD83D\uDCAA',
          cue: 'One set to absolute failure with perfect form. Record every Friday.',
          formChecks: ['perfect form only', 'count every rep', 'stop at failure'],
        },
        {
          name: 'Sit-Ups \u2014 60 Second',
          type: 'BENCHMARK',
          sets: '1 set',
          reps: '60 sec max',
          durationSec: 60,
          icon: '\u23F1',
          cue: 'Max sit-ups in 60 seconds with good form. Core endurance benchmark.',
          formChecks: ['full range', 'no neck strain', 'consistent pace'],
        },
        {
          name: 'Plank Max Hold',
          type: 'BENCHMARK',
          sets: '1 max hold',
          reps: 'max time',
          durationSec: 0,
          icon: '\uD83D\uDCCF',
          cue: 'Hold as long as possible with perfect form. Record your max time every Friday.',
          formChecks: ['perfect form only', 'breathe steadily', 'stop cleanly'],
        },
        {
          name: '100 Calf Raises Timed',
          type: 'BENCHMARK',
          sets: '1 set',
          reps: '100 \u2014 time it',
          durationSec: 0,
          icon: '\uD83E\uDDB5',
          cue: 'Both legs, standing. Record your time every Friday.',
          formChecks: ['full range', 'count accurately', 'consistent pace'],
        },
        {
          name: 'Stride-Out Run',
          type: 'RUNNING',
          sets: '5 reps',
          reps: '40m each',
          durationSec: 0,
          icon: '\uD83D\uDCA8',
          cue: '40m at 80% effort. Tall posture, forward lean, heel flicking up behind you.',
          formChecks: ['tall posture', 'forward lean', 'heel up behind'],
        },
      ],
    },
  ],
};

export const ONBOARDING_QUESTIONS = [
  {
    id: 'age',
    type: 'number',
    unit: 'yrs',
    placeholder: 'e.g. 13',
    question: 'How old are you?',
    subtitle: 'Helps calibrate intensity for your age',
    bubble: "Hey! I'm Rex\nLet's build your\npersonalised plan!",
  },
  {
    id: 'gender',
    type: 'choice',
    question: 'Your gender?',
    subtitle: 'Optional \u2014 helps personalise further',
    optional: true,
    options: [
      { icon: '\uD83D\uDC68', label: 'Male', value: 'male' },
      { icon: '\uD83D\uDC69', label: 'Female', value: 'female' },
      { icon: '\uD83E\uDDD1', label: 'Other', value: 'other' },
      { icon: '\uD83E\uDD10', label: 'Prefer not to say', value: 'skip' },
    ],
  },
  {
    id: 'height',
    type: 'number',
    unit: 'cm',
    placeholder: 'e.g. 180',
    question: 'Your height?',
    subtitle: 'Used to personalise movement range',
  },
  {
    id: 'weight',
    type: 'number',
    unit: 'kg',
    placeholder: 'e.g. 70',
    question: 'Your weight?',
    subtitle: 'Calibrates bodyweight exercise difficulty',
  },
  {
    id: 'sport',
    type: 'choice',
    question: 'Your main sport?',
    subtitle: "We'll add sport-specific drills",
    options: [
      { icon: '\u26BD', label: 'Soccer / Football', value: 'soccer' },
      { icon: '\uD83C\uDFC0', label: 'Basketball', value: 'basketball' },
      { icon: '\uD83C\uDFC8', label: 'American Football', value: 'football' },
      { icon: '\uD83C\uDFC3', label: 'Track & Field', value: 'track' },
      { icon: '\uD83E\uDD4A', label: 'Combat Sports', value: 'combat' },
      { icon: '\uD83C\uDFCA', label: 'Swimming', value: 'swimming' },
      { icon: '\u270F\uFE0F', label: 'Other...', value: 'other' },
    ],
  },
  {
    id: 'skillFocus',
    type: 'multi',
    question: 'Skill focus areas?',
    subtitle: "Pick all that apply \u2014 we'll prioritise these",
    options: [
      { icon: '\u26A1', label: 'Speed', value: 'speed' },
      { icon: '\uD83D\uDCAA', label: 'Strength', value: 'strength' },
      { icon: '\uD83D\uDD01', label: 'Agility', value: 'agility' },
      { icon: '\u2764\uFE0F', label: 'Endurance', value: 'endurance' },
      { icon: '\uD83E\uDDD8', label: 'Mobility', value: 'mobility' },
    ],
  },
  {
    id: 'level',
    type: 'choice',
    question: 'Experience level?',
    subtitle: "Be honest \u2014 we'll adjust as you improve",
    options: [
      { icon: '\uD83C\uDF31', label: 'Beginner', value: 'beginner' },
      { icon: '\u26A1', label: 'Intermediate', value: 'intermediate' },
      { icon: '\uD83D\uDE80', label: 'Advanced', value: 'advanced' },
    ],
  },
  {
    id: 'equipment',
    type: 'multi',
    question: 'Available equipment?',
    subtitle: 'Pick all that apply',
    options: [
      { icon: '\uD83E\uDD38', label: 'No equipment', value: 'none' },
      { icon: '\uD83C\uDFCB\uFE0F', label: 'Dumbbells', value: 'dumbbells' },
      { icon: '\u27B0', label: 'Resistance Bands', value: 'bands' },
      { icon: '\uD83C\uDFDF\uFE0F', label: 'Full Gym', value: 'gym' },
    ],
  },
  {
    id: 'sessionLen',
    type: 'choice',
    question: 'Session length?',
    subtitle: "We'll fit maximum value into your time",
    twoCol: true,
    options: [
      { icon: '\u26A1', label: '20 min', value: 20 },
      { icon: '\uD83D\uDD25', label: '30 min', value: 30 },
      { icon: '\uD83D\uDCAA', label: '45 min', value: 45 },
      { icon: '\uD83C\uDFC6', label: '60+ min', value: 60 },
    ],
  },
  {
    id: 'daysPerWeek',
    type: 'choice',
    question: 'Days per week?',
    subtitle: 'More days = faster results',
    twoCol: true,
    options: [
      { icon: '\uD83D\uDE0C', label: '2 days', value: 2 },
      { icon: '\uD83D\uDC4C', label: '3 days', value: 3 },
      { icon: '\uD83D\uDCAA', label: '4 days', value: 4 },
      { icon: '\uD83D\uDD25', label: '5 days', value: 5 },
      { icon: '\u26A1', label: '6 days', value: 6 },
    ],
  },
  {
    id: 'intensity',
    type: 'choice',
    question: 'Intensity preference?',
    subtitle: 'How hard do you want to be pushed?',
    options: [
      { icon: '\uD83E\uDEB6', label: 'Light', value: 'light' },
      { icon: '\u2696\uFE0F', label: 'Moderate', value: 'moderate' },
      { icon: '\uD83D\uDD25', label: 'Intense', value: 'intense' },
      { icon: '\uD83D\uDC80', label: 'Extreme', value: 'extreme' },
    ],
  },
];

export const ACHIEVEMENTS = [
  { id: 'first', icon: '\uD83E\uDD47', name: 'First Workout!', desc: 'Complete your first session' },
  { id: 's3', icon: '\uD83D\uDD25', name: '3-Day Streak', desc: '3 consecutive training days' },
  { id: 's7', icon: '\uD83D\uDD25', name: 'Week Warrior', desc: '7-day streak' },
  { id: 'noskip', icon: '\uD83D\uDEE1\uFE0F', name: 'No Skip Week', desc: '7 days, zero skips' },
  { id: 'iron', icon: '\u2699\uFE0F', name: 'Iron Discipline', desc: '30 days no skips' },
  { id: 'perf', icon: '\u2728', name: 'Perfect Form', desc: 'Score 90%+ form on a session' },
  { id: 'lv5', icon: '\u2B50', name: 'Level 5', desc: 'Reach level 5' },
  { id: 'c5', icon: '\uD83C\uDFC5', name: 'Consistent', desc: 'Complete 5 workouts' },
];

export const SHOP_ITEMS = [
  {
    category: 'Daily Use',
    items: [
      { icon: '\u26A1', name: 'XP Boost', desc: 'Double XP for next workout', cost: 10, id: 'xpboost' },
      { icon: '\u2764\uFE0F', name: 'Energy Refill', desc: 'Restore discipline after penalties', cost: 8, id: 'energyrefill' },
      { icon: '\uD83C\uDFAB', name: 'Skip Token', desc: 'Skip 1 exercise without penalty', cost: 20, id: 'skiptoken' },
    ],
  },
  {
    category: 'Strategic',
    items: [
      { icon: '\uD83D\uDEE1\uFE0F', name: 'Streak Shield', desc: 'Protects streak if you miss a day', cost: 25, id: 'streakshield' },
      { icon: '\uD83D\uDD01', name: 'XP Recovery', desc: 'Recover 50% of lost XP from last skip', cost: 30, id: 'xprecovery' },
    ],
  },
  {
    category: 'Progression',
    items: [
      { icon: '\uD83D\uDD13', name: 'Advanced Workouts', desc: 'Unlock elite training paths', cost: 100, id: 'advancedwk' },
      { icon: '\uD83E\uDD16', name: 'AI Coach Upgrade', desc: 'Deeper form feedback & analysis', cost: 150, id: 'aicoach' },
      { icon: '\uD83C\uDFAF', name: 'Custom Training Focus', desc: 'Reshapes plan around your top priority', cost: 80, id: 'customfocus' },
    ],
  },
];

export const LEADERBOARD_DATA = [
  { name: 'Jordan K.', xp: 2840, streak: 14, disc: 180, avatar: '\uD83C\uDFC0', me: false },
  { name: 'Marcus T.', xp: 2210, streak: 8, disc: 140, avatar: '\u26A1', me: false },
  { name: 'YOU', xp: 0, streak: 0, disc: 0, avatar: '\uD83E\uDD85', me: true },
  { name: 'Alex R.', xp: 1890, streak: 5, disc: 120, avatar: '\uD83D\uDD25', me: false },
  { name: 'Sam L.', xp: 1540, streak: 3, disc: 90, avatar: '\uD83D\uDCAA', me: false },
  { name: 'Chris P.', xp: 1200, streak: 2, disc: 70, avatar: '\uD83C\uDFC3', me: false },
  { name: 'Taylor B.', xp: 980, streak: 1, disc: 50, avatar: '\u2B50', me: false },
  { name: 'Riley H.', xp: 720, streak: 0, disc: 30, avatar: '\uD83C\uDF31', me: false },
  { name: 'Drew M.', xp: 450, streak: 0, disc: 15, avatar: '\uD83D\uDE24', me: false },
  { name: 'Jamie C.', xp: 200, streak: 0, disc: 5, avatar: '\uD83E\uDD1D', me: false },
];
